# Generated by Django 5.0.6 on 2024-08-08 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('courier_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.couriershops')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'delivery',
                'ordering': ['-delivery_date'],
                'indexes': [models.Index(fields=['tracking_number'], name='delivery_trackin_36d795_idx'), models.Index(fields=['delivery_date', 'status'], name='delivery_deliver_9d80af_idx')],
            },
        ),
    ]
