# Generated by Django 5.0.7 on 2024-08-12 05:46

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_couriershops_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='delivery',
            new_name='my_app_deli_trackin_0be6b8_idx',
            old_name='delivery_trackin_36d795_idx',
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='my_app_deli_deliver_46ae50_idx',
            old_name='delivery_deliver_9d80af_idx',
        ),
        migrations.AlterField(
            model_name='couriershops',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[my_app.models.validate_ten_digits]),
        ),
        migrations.AlterField(
            model_name='couriershops',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[my_app.models.validate_ten_digits]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[my_app.models.validate_ten_digits]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[my_app.models.validate_ten_digits]),
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='my_app_delivery',
        ),
    ]
