# Generated by Django 5.0.7 on 2024-08-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_delivery_trackin_36d795_idx_my_app_deli_trackin_0be6b8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
